### ISSUE TITLE
Failed to create datagram socket (OS Error: Too many open files, errno = 24)

### ISSUE THREAD

**Issue by git-elliot** [osociety/vernet#150]
Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Too many open files, errno = 24), address = , port = 5353
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1051:7)
<asynchronous suspension>
#1      _RawDatagramSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:2558:15)
<asynchronous suspension>
#2      MDnsClient.start (package:multicast_dns/multicast_dns.dart:135:40)
<asynchronous suspension>
#3      MdnsScannerServiceImpl.findingMdnsWithAddress (package:network_tools/src/services/impls/mdns_scanner_service_impl.dart:73:5)
<asynchronous suspension>

**Comment by git-elliot** [comment]
Seems like we have to run this search in isolate.

**Comment by git-elliot** [comment]
Not seen nowadays, will open again if it occurs.
